[package]
authors = ["Langston Barrett <langston.barrett@gmail.com>"]
autoexamples = false
categories = ["parser-implementations", "parsing", "text-editors"]
description = "Cryptol grammar for tree-sitter"
edition = "2024"
keywords = ["incremental", "parsing", "tree-sitter", "cryptol"]
license = "MIT"
name = "tree-sitter-cryptol"
readme = "README.md"
repository = "https://github.com/langston-barrett/tree-sitter-cryptol"
version = "0.1.0"

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "expression/grammar.js",
  "expression/src/*",
  "grammar.js",
  "queries/*",
  "src/*",
  "type/grammar.js",
  "type/src/*",
  "tree-sitter.json",
  "/LICENSE",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.27.1"
